function defineArchInterfaces()
%DEFINEARCHINTERFACES Create and assign typed interfaces for LogisticsArchitecture.
%   Builds LogisticsInterfaces.sldd, links it to the architecture model, and
%   assigns an interface to every architecture port.

dictFile = 'LogisticsInterfaces.sldd';
model = systemcomposer.loadModel('LogisticsArchitecture');

if exist(dictFile, 'file')
    dict = systemcomposer.openDictionary(dictFile);
else
    dict = systemcomposer.createDictionary(dictFile);
end

% interfaceName -> elements
spec = { ...
    'SupplyConvoy',      {'Trucks', 'CargoTons'}; ...
    'ThreatAction',      {'AmbushProb', 'Posture'}; ...
    'SupplyStatus',      {'StockTons', 'DaysOfSupply'}; ...
    'ConvoyStatus',      {'ConvoysEnRoute', 'TonsLost'}; ...
    'RouteOrder',        {'RouteId'}; ...
    'InterdictionOrder', {'Posture'}};

for i = 1:size(spec, 1)
    name = spec{i, 1};
    if isempty(dict.getInterface(name))
        intf = dict.addInterface(name);
        for e = spec{i, 2}
            intf.addElement(e{1});
        end
    end
end
dict.save();

try
    model.linkDictionary(dictFile);
catch e
    if ~contains(e.message, 'already')
        rethrow(e);
    end
end

% componentPath (empty = root), portName, interfaceName
assignments = { ...
    'LogisticsArchitecture/BlueForce',                              'ThreatNorth',  'ThreatAction'; ...
    'LogisticsArchitecture/BlueForce',                              'ThreatSouth',  'ThreatAction'; ...
    'LogisticsArchitecture/RedForce',                               'ThreatNorth',  'ThreatAction'; ...
    'LogisticsArchitecture/RedForce',                               'ThreatSouth',  'ThreatAction'; ...
    'LogisticsArchitecture/BlueForce/LogisticsSupportArea',         'Convoys',      'SupplyConvoy'; ...
    'LogisticsArchitecture/BlueForce/LogisticsSupportArea',         'RouteOrder',   'RouteOrder'; ...
    'LogisticsArchitecture/BlueForce/ConvoyForce',                  'Convoys',      'SupplyConvoy'; ...
    'LogisticsArchitecture/BlueForce/ConvoyForce',                  'Deliveries',   'SupplyConvoy'; ...
    'LogisticsArchitecture/BlueForce/ConvoyForce',                  'ConvoyStatus', 'ConvoyStatus'; ...
    'LogisticsArchitecture/BlueForce/ConvoyForce',                  'ThreatNorth',  'ThreatAction'; ...
    'LogisticsArchitecture/BlueForce/ConvoyForce',                  'ThreatSouth',  'ThreatAction'; ...
    'LogisticsArchitecture/BlueForce/ForwardOperatingBase',         'Deliveries',   'SupplyConvoy'; ...
    'LogisticsArchitecture/BlueForce/ForwardOperatingBase',         'SupplyStatus', 'SupplyStatus'; ...
    'LogisticsArchitecture/BlueForce/SustainmentC2',                'SupplyStatus', 'SupplyStatus'; ...
    'LogisticsArchitecture/BlueForce/SustainmentC2',                'ConvoyStatus', 'ConvoyStatus'; ...
    'LogisticsArchitecture/BlueForce/SustainmentC2',                'RouteOrder',   'RouteOrder'; ...
    'LogisticsArchitecture/RedForce/RedC2',                         'OrdersNorth',  'InterdictionOrder'; ...
    'LogisticsArchitecture/RedForce/RedC2',                         'OrdersSouth',  'InterdictionOrder'; ...
    'LogisticsArchitecture/RedForce/InterdictionCellNorth',         'Orders',       'InterdictionOrder'; ...
    'LogisticsArchitecture/RedForce/InterdictionCellNorth',         'Threat',       'ThreatAction'; ...
    'LogisticsArchitecture/RedForce/InterdictionCellSouth',         'Orders',       'InterdictionOrder'; ...
    'LogisticsArchitecture/RedForce/InterdictionCellSouth',         'Threat',       'ThreatAction'};

nSet = 0;
for i = 1:size(assignments, 1)
    comp = model.lookup(Path=assignments{i, 1});
    ports = comp.Architecture.Ports;
    idx = strcmp({ports.Name}, assignments{i, 2});
    if ~any(idx)
        warning('port %s not found on %s', assignments{i, 2}, assignments{i, 1});
        continue
    end
    ports(idx).setInterface(dict.getInterface(assignments{i, 3}));
    nSet = nSet + 1;
end

model.save();
fprintf('Assigned interfaces to %d of %d ports.\n', nSet, size(assignments, 1));
end
